### PR TITLE
Devtools eslint

### PR DESCRIPTION
**Pull request by eeejay**

### CODE REVIEW

**Comment by eeejay** [comment]
This fixes issue #35

**Comment by dylanb** [comment]
@eeejay 2 issues

We would prefer to keep the tabs rather than spaces for the current files. The coding guideline seems to allow either tabs or spaces but not mixed. Can you change all whitespace to tabs.

Also, before merging, we will need the CLA signed.

**Comment by eeejay** [comment]
A quick grep in the browser's devtools source shows that they don't use tabs in JS. The only exception are upstream files that are pulled in externally.

**Comment by dylanb** [comment]
Not being allowed is different from not being used. From the eslint setup, it looks like its allowed. If that is the case, it would result in fewer changed lines which means we could keep more of our blame history.

**Comment by eeejay** [comment]
It is not allowed. Both the devtools style guide and the Mozilla one
prohibit it.
https://wiki.mozilla.org/DevTools/CodingStandards#Code_style
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style

As for git blame, that is why this change needs to happen earlier rather
than later.

**Pull request merged**
